### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by asmeurer** [takluyver/IRkernel#60]
Are you planning uploading this to CRAN?

If not, can you at least tag a release? I'm trying to build a conda package from this, and I'd like to have a stable release point other than just "master" to build off of.

**Comment by takluyver** [comment]
I can certainly make an arbitrary tag, but at the moment I'm generally expecting that people run from master.

It will probably end up on CRAN one day, but currently the binary packages for rzmq are out of date or not even there.

**Comment by asmeurer** [comment]
This is a problem I'm running into with a lot of R packages that are hosted only on GitHub. How do I version a conda package for an R package that is expected to be installed from master? Also, does this mean that I should build a new version every time you make a commit?

**Comment by takluyver** [comment]
I've just pushed a 0.1 tag, so you have something to build against.

I think the situation arises because CRAN is a manually curated repository - you have to get packages approved, you don't just upload them like on PyPI. So if you're doing something small or quick, it's easier just to tell people to get it from Github. I don't know what they'd say about a package like IRkernel, and I'm not especially looking forward to finding out.

I think projects that are packaged directly from a VCS often get a version number like 0.1-yyyymmdd-n (i.e. structured in a way that it sorts correctly with respect to actual releases).

**Comment by asmeurer** [comment]
Yeah, I've been contemplating using `git describe` to generate a version number. But that requires at least one tag (hence this issue).
